-- MySQL Script generated by MySQL Workbench
-- fr. 29. jan. 2016 kl. 10.47 +0100
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema so_dump
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `so_dump` ;

-- -----------------------------------------------------
-- Schema so_dump
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `so_dump` DEFAULT CHARACTER SET utf8 ;
USE `so_dump` ;

-- -----------------------------------------------------
-- Table `so_dump`.`Votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump`.`Votes` ;

CREATE TABLE IF NOT EXISTS `so_dump`.`Votes` (
  `Id` INT NOT NULL,
  `PostId` INT NULL,
  `VoteTypeId` INT NULL,
  `CreationDate` DATETIME NULL,
  `UserId` INT NULL,
  `BountyAmount` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `so_dump`.`Badges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump`.`Badges` ;

CREATE TABLE IF NOT EXISTS `so_dump`.`Badges` (
  `UserId` INT NULL,
  `Name` VARCHAR(255) NULL,
  `Date` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `so_dump`.`Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump`.`Posts` ;

CREATE TABLE IF NOT EXISTS `so_dump`.`Posts` (
  `Id` INT NOT NULL,
  `PostTypeId` INT NULL,
  `ParentID` INT NULL,
  `AcceptedAnswerId` INT NULL,
  `CreationDate` DATETIME NULL,
  `Score` INT NULL,
  `ViewCount` INT NULL,
  `Body` LONGTEXT NULL,
  `OwnerUserId` INT NULL,
  `LastEditorUserId` INT NULL,
  `LastEditorDisplayName` VARCHAR(255) NULL,
  `LastEditDate` DATETIME NULL,
  `LastActivityDate` DATETIME NULL,
  `CommunityOwnedDate` DATETIME NULL,
  `ClosedDate` DATETIME NULL,
  `Title` VARCHAR(255) NULL,
  `Tags` VARCHAR(255) NULL,
  `AnswerCount` INT NULL,
  `CommentCount` INT NULL,
  `FavoriteCount` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `so_dump`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump`.`Comments` ;

CREATE TABLE IF NOT EXISTS `so_dump`.`Comments` (
  `Id` INT NOT NULL,
  `PostId` INT NULL,
  `Score` INT NULL,
  `Text` LONGTEXT NULL,
  `CreationDate` DATETIME NULL,
  `UserId` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `so_dump`.`PostLinks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump`.`PostLinks` ;

CREATE TABLE IF NOT EXISTS `so_dump`.`PostLinks` (
  `Id` INT NOT NULL,
  `CreationDate` DATETIME NULL,
  `PostId` INT NULL,
  `RelatedPostId` INT NULL,
  `PostLinkTypeId` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `so_dump`.`PostHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump`.`PostHistory` ;

CREATE TABLE IF NOT EXISTS `so_dump`.`PostHistory` (
  `Id` INT NOT NULL,
  `PostHistoryTypeId` INT NULL,
  `PostId` VARCHAR(45) NULL,
  `RevisionGUID` VARCHAR(255) NULL,
  `CreationDate` DATETIME NULL,
  `UserId` INT NULL,
  `UserDisplayName` VARCHAR(255) NULL,
  `Comment` LONGTEXT NULL,
  `Text` LONGTEXT NULL,
  `CloseReasonId` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `so_dump`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump`.`Users` ;

CREATE TABLE IF NOT EXISTS `so_dump`.`Users` (
  `Id` INT NOT NULL,
  `Reputation` INT NULL,
  `CreationDate` DATETIME NULL,
  `DisplayName` VARCHAR(255) NULL,
  `EmailHash` VARCHAR(255) NULL,
  `LastAccessDate` DATETIME NULL,
  `WebsiteUrl` VARCHAR(45) NULL,
  `Location` VARCHAR(255) NULL,
  `Age` INT NULL,
  `AboutMe` VARCHAR(255) NULL,
  `Views` INT NULL,
  `UpVotes` INT NULL,
  `DownVotes` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `so_dump`.`Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump`.`Tags` ;

CREATE TABLE IF NOT EXISTS `so_dump`.`Tags` (
  `Id` INT NOT NULL,
  `TagName` VARCHAR(255) NULL,
  `ExcerptPostId` INT NULL,
  `WikiPostId` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
