-- MySQL Script generated by MySQL Workbench
-- on. 06. april 2016 kl. 04.33 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema so_dump_march
-- -----------------------------------------------------
-- DROP SCHEMA IF EXISTS `so_dump_march` ;

-- -----------------------------------------------------
-- Schema so_dump_march
-- -----------------------------------------------------
-- CREATE SCHEMA IF NOT EXISTS `so_dump_march` DEFAULT CHARACTER SET utf8 ;
USE `so_dump_march` ;

-- -----------------------------------------------------
-- Table `so_dump_march`.`Votes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump_march`.`Votes` ;

CREATE TABLE IF NOT EXISTS `so_dump_march`.`Votes` (
  `Id` INT NOT NULL,
  `PostId` INT NULL,
  `VoteTypeId` INT NULL,
  `CreationDate` DATETIME NULL,
  `UserId` INT NULL,
  `BountyAmount` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `so_dump_march`.`Badges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump_march`.`Badges` ;

CREATE TABLE IF NOT EXISTS `so_dump_march`.`Badges` (
  `UserId` INT NULL,
  `Name` VARCHAR(255) NULL,
  `Date` DATETIME NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `so_dump_march`.`Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump_march`.`Posts` ;

CREATE TABLE IF NOT EXISTS `so_dump_march`.`Posts` (
  `Id` INT NOT NULL,
  `PostTypeId` INT NULL,
  `ParentID` INT NULL,
  `AcceptedAnswerId` INT NULL,
  `CreationDate` DATETIME NULL,
  `Score` INT NULL,
  `ViewCount` INT NULL,
  `Body` LONGTEXT NULL,
  `OwnerUserId` INT NULL,
  `LastEditorUserId` INT NULL,
  `LastEditorDisplayName` VARCHAR(255) NULL,
  `LastEditDate` DATETIME NULL,
  `LastActivityDate` DATETIME NULL,
  `CommunityOwnedDate` DATETIME NULL,
  `ClosedDate` DATETIME NULL,
  `Title` VARCHAR(255) NULL,
  `Tags` VARCHAR(255) NULL,
  `AnswerCount` INT NULL,
  `CommentCount` INT NULL,
  `FavoriteCount` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `so_dump_march`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump_march`.`Comments` ;

CREATE TABLE IF NOT EXISTS `so_dump_march`.`Comments` (
  `Id` INT NOT NULL,
  `PostId` INT NULL,
  `Score` INT NULL,
  `Text` LONGTEXT NULL,
  `CreationDate` DATETIME NULL,
  `UserId` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `so_dump_march`.`PostLinks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump_march`.`PostLinks` ;

CREATE TABLE IF NOT EXISTS `so_dump_march`.`PostLinks` (
  `Id` INT NOT NULL,
  `CreationDate` DATETIME NULL,
  `PostId` INT NULL,
  `RelatedPostId` INT NULL,
  `PostLinkTypeId` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `so_dump_march`.`PostHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump_march`.`PostHistory` ;

CREATE TABLE IF NOT EXISTS `so_dump_march`.`PostHistory` (
  `Id` INT NOT NULL,
  `PostHistoryTypeId` INT NULL,
  `PostId` VARCHAR(45) NULL,
  `RevisionGUID` VARCHAR(255) NULL,
  `CreationDate` DATETIME NULL,
  `UserId` INT NULL,
  `UserDisplayName` VARCHAR(255) NULL,
  `Comment` LONGTEXT NULL,
  `Text` LONGTEXT NULL,
  `CloseReasonId` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `so_dump_march`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump_march`.`Users` ;

CREATE TABLE IF NOT EXISTS `so_dump_march`.`Users` (
  `Id` INT NOT NULL,
  `Reputation` INT NULL,
  `CreationDate` DATETIME NULL,
  `DisplayName` VARCHAR(255) NULL,
  `EmailHash` VARCHAR(255) NULL,
  `LastAccessDate` DATETIME NULL,
  `WebsiteUrl` VARCHAR(45) NULL,
  `Location` VARCHAR(255) NULL,
  `Age` INT NULL,
  `AboutMe` VARCHAR(255) NULL,
  `Views` INT NULL,
  `UpVotes` INT NULL,
  `DownVotes` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `so_dump_march`.`Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump_march`.`Tags` ;

CREATE TABLE IF NOT EXISTS `so_dump_march`.`Tags` (
  `Id` INT NOT NULL,
  `TagName` VARCHAR(255) NULL,
  `ExcerptPostId` INT NULL,
  `WikiPostId` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `so_dump_march`.`posvote_Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump_march`.`posvote_Posts` ;

CREATE TABLE IF NOT EXISTS `so_dump_march`.`posvote_Posts` (
  `Id` INT NOT NULL,
  `PostTypeId` INT NULL,
  `ParentID` INT NULL,
  `AcceptedAnswerId` INT NULL,
  `CreationDate` DATETIME NULL,
  `Score` INT NULL,
  `ViewCount` INT NULL,
  `Body` LONGTEXT NULL,
  `OwnerUserId` INT NULL,
  `LastEditorUserId` INT NULL,
  `LastEditorDisplayName` VARCHAR(255) NULL,
  `LastEditDate` DATETIME NULL,
  `LastActivityDate` DATETIME NULL,
  `CommunityOwnedDate` DATETIME NULL,
  `ClosedDate` DATETIME NULL,
  `Title` VARCHAR(255) NULL,
  `Tags` VARCHAR(255) NULL,
  `AnswerCount` INT NULL,
  `CommentCount` INT NULL,
  `FavoriteCount` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `so_dump_march`.`negvote_Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `so_dump_march`.`negvote_Posts` ;

CREATE TABLE IF NOT EXISTS `so_dump_march`.`negvote_Posts` (
  `Id` INT NOT NULL,
  `PostTypeId` INT NULL,
  `ParentID` INT NULL,
  `AcceptedAnswerId` INT NULL,
  `CreationDate` DATETIME NULL,
  `Score` INT NULL,
  `ViewCount` INT NULL,
  `Body` LONGTEXT NULL,
  `OwnerUserId` INT NULL,
  `LastEditorUserId` INT NULL,
  `LastEditorDisplayName` VARCHAR(255) NULL,
  `LastEditDate` DATETIME NULL,
  `LastActivityDate` DATETIME NULL,
  `CommunityOwnedDate` DATETIME NULL,
  `ClosedDate` DATETIME NULL,
  `Title` VARCHAR(255) NULL,
  `Tags` VARCHAR(255) NULL,
  `AnswerCount` INT NULL,
  `CommentCount` INT NULL,
  `FavoriteCount` INT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
